/*
 Frame donde se ejecutarán todos lo9s ejercicios
 */
package recup_parcial_02_alvarezcarlos;

import java.util.ArrayList;
import java.util.Date;
import java.util.TreeMap;

/**
 *
 * @author Alumno
 */
public class FrameR extends javax.swing.JFrame {

    /**
     * Creates new form FrameR
     */
    public FrameR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ejer1 = new javax.swing.JButton();
        ejer2 = new javax.swing.JButton();
        ejer3 = new javax.swing.JButton();
        ejer4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ejer1.setText("ejer1");
        ejer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejer1ActionPerformed(evt);
            }
        });

        ejer2.setText("ejer2");
        ejer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejer2ActionPerformed(evt);
            }
        });

        ejer3.setText("ejer3");
        ejer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejer3ActionPerformed(evt);
            }
        });

        ejer4.setText("ejer4");
        ejer4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejer4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ejer1)
                    .addComponent(ejer2)
                    .addComponent(ejer3)
                    .addComponent(ejer4))
                .addContainerGap(333, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(ejer1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ejer2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ejer3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ejer4)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ejer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejer1ActionPerformed
        //Hice las clases
    }//GEN-LAST:event_ejer1ActionPerformed

    private void ejer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejer2ActionPerformed
        System.out.println("\n_______________________________________________________");
        //Creao profecionales
        Profesional prof1 = new Profesional(01, "Week", "John", new Date(1989, 04, 03), 4290, new TreeMap<Integer, Especialidad>());
        Profesional prof2 = new Profesional(02, "DiMacio","Casia", new Date(1987, 07, 02), 2213, new TreeMap<Integer, Especialidad>());

        //Creo pacientes
        Paciente pac1 = new Paciente(01, "Lopez", "Alverto", new Date(1999, 04, 04), 27439097, "23454555", "calle2");
        Paciente pac2 = new Paciente(02, "Cardenas", "Ana", new Date(1997, 02, 04), 27439097, "23454555", "calle2");
        Paciente pac6 = new Paciente(06, "Perez", "Sofía", new Date(1997, 05, 11), 27439097, "23454555", "calle2");
        
        //Creo Secretaria
        Empleado emp1 = new Empleado("Secretaria", 01, "Sosa", "Shirly", new Date(1998, 03, 02));

        //Creo turnos
        Turno turno1 = new Turno();
        turno1.setFecha(new Date(2023, 3, 1));
        turno1.setPaciente(pac1);
        turno1.setResponsable(emp1);
        
        Turno turno2 = new Turno();
        turno2.setFecha(new Date(2023, 9, 12));
        turno2.setPaciente(pac1);
        turno2.setResponsable(emp1);
        
        Turno turno3 = new Turno();
        turno3.setFecha(new Date(2023, 9, 12));
        turno3.setPaciente(pac6);
        turno3.setResponsable(emp1);
        
        //creo especialidades
        Especialidad esp1 = new Especialidad();
        esp1.setId(01);
        esp1.setNombreEsp("Radiología");
        Especialidad esp2 = new Especialidad();
        esp2.setId(02);
        esp2.setNombreEsp("Traumatología");
        Especialidad esp3 = new Especialidad();
        esp3.setId(03);
        esp3.setNombreEsp("Pediatría");      

        //Genero turnos
        prof1.agendarTurno(esp1, turno1);
        prof1.agendarTurno(esp1, turno2);
        
        prof2.agendarTurno(esp2, turno1);
        
        //Genero una lista de turnos
        ArrayList<Turno> listaTur=new ArrayList();
        
        //Agrego turnos a la lista
        listaTur.add(turno1);
        listaTur.add(turno2);
        listaTur.add(turno3);
        
        
        String buscar_pac = pac1.toString();
        
        for(int i=0;i<listaTur.size();i++){ //Recorre cada turno dentro de la lista 
            Turno t = listaTur.get(i); //toma cada turno
            if("Lopez Alverto".equals(t.getPaciente().toString())){
                System.out.println("\nNroTurno: "+t.getNro() + "\nPaciente:" + t.getPaciente().toString()+"\nSecretaria: "+t.getResponsable());
            }
        
        }    
    
    
    }//GEN-LAST:event_ejer2ActionPerformed

    private void ejer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejer3ActionPerformed
            //Creao profecionales
        Profesional prof1 = new Profesional(01, "Week", "John", new Date(1989, 04, 03), 4290, new TreeMap<Integer, Especialidad>());
        Profesional prof2 = new Profesional(02, "José","Gonzales", new Date(1987, 07, 02), 2213, new TreeMap<Integer, Especialidad>());

        //Creo pacientes
        Paciente pac1 = new Paciente(01, "Lopez", "Alverto", new Date(1999, 04, 04), 27439097, "23454555", "calle2");
        Paciente pac2 = new Paciente(02, "Cardenas", "Ana", new Date(1997, 02, 04), 27439097, "23454555", "calle2");
        Paciente pac6 = new Paciente(06, "Perez", "Sofía", new Date(1997, 05, 11), 27439097, "23454555", "calle2");
        
        //Creo Secretaria
        Empleado emp1 = new Empleado("Secretaria", 01, "Sosa", "Shirly", new Date(1998, 03, 02));

        //Creo turnos
        Turno turno1 = new Turno();
        turno1.setFecha(new Date(2023, 3, 1));
        turno1.setPaciente(pac1);
        turno1.setResponsable(emp1);
        
        Turno turno2 = new Turno();
        turno2.setFecha(new Date(2023, 9, 12));
        turno2.setPaciente(pac1);
        turno2.setResponsable(emp1);
        
        Turno turno3 = new Turno();
        turno3.setFecha(new Date(2023, 9, 12));
        turno3.setPaciente(pac6);
        turno3.setResponsable(emp1);
        
        //creo especialidades
        Especialidad esp1 = new Especialidad();
        esp1.setId(01);
        esp1.setNombreEsp("Radiología");
        Especialidad esp2 = new Especialidad();
        esp2.setId(02);
        esp2.setNombreEsp("Traumatología");
        Especialidad esp3 = new Especialidad();
        esp3.setId(03);
        esp3.setNombreEsp("Pediatría");      

        //Genero turnos
        prof1.agendarTurno(esp1, turno1);
        prof1.agendarTurno(esp1, turno2);
        
        prof2.agendarTurno(esp2, turno1);
        
        //Genero una lista de profecionales
        ArrayList<Profesional> listapr=new ArrayList();
        
        //Agrego profecionales a la lista
        listapr.add(prof1);
        listapr.add(prof2);
        
        
        
        String buscar_pr = prof2.toString();
        
        for(int i=0;i<listapr.size();i++){ 
            Profesional p = listapr.get(i);
            if("José Gonzales".equals(p.toString())){
                p.listarTurnosPorEspecialidad();
            }
        
        } 
    }//GEN-LAST:event_ejer3ActionPerformed

    private void ejer4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejer4ActionPerformed
        ArrayList<Recurso> recursos = new ArrayList<>();
        
        recursos.add( new Recurso(0, "computadora", "electronica", "32 pulgadas, gris, W10"));
        recursos.add( new Recurso(1, "silla", "mueble de oficina", "ploastico"));
        recursos.add( new Recurso(2, "escritorio", "mueble de oficina", "madera, marrón"));
        recursos.add( new Recurso(3, "cama", "mueble de dormitorio", "Dos Plazas"));
        recursos.add( new Recurso(4, "cama", "mueble de dormitorio", "Una plaza"));
        recursos.add( new Recurso(5, "cama", "mueble de dormitorio", "Una plaza"));
        recursos.add( new Recurso(6, "computadora", "electronica", "32 pulgadas, negro, W10"));
        recursos.add( new Recurso(7, "computadora", "electronica", "42 pulgadas, negro"));
        recursos.add( new Recurso(8, "escritorio", "mueble de oficina", "metal, blanco"));
        recursos.add( new Recurso(9, "silla", "mueble", "madera, marrón"));
        //creamos dos contadores
        int contcomp = 0;
        int contmu = 0;
  
        
        for(int i  = 0; i < recursos.size(); i++){ 
            if(recursos.get(i).getTipoRecurso() == "mueble de oficina"){ 
                contmu +=1;              
            }
            if(recursos.get(i).getNombre() == "computadora"){
                contcomp +=1;
            }
        }
        
        System.out.println("En el edificio hay: ");
        System.out.println("Hay " + contmu+" muebles de oficina.");
        System.out.println("Hay " + contcomp +" computadoras.");
    }//GEN-LAST:event_ejer4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ejer1;
    private javax.swing.JButton ejer2;
    private javax.swing.JButton ejer3;
    private javax.swing.JButton ejer4;
    // End of variables declaration//GEN-END:variables
}
